### PR TITLE
Multi-csv feature added, display export data on the example site

### PR DESCRIPTION
**Pull request by shaohaolin**
###  Multi-csv feature:

When `multi-csv` is set it to `true`, it allows to convert an object of nested arrays to different csv in one file.
Sampe input data:
`{ managers: [ {name: John, age: 45}, {name: Matt, age: 36}],`
 ` employees: [ {name: Justin, gender: male, age:27, {name: Mary, gender: female, age: 22}, {name: Joe, gender: male, age 31}}] 
}`
Output csv:

### Display sample data on the site:

Being able to display the sample on the site helps to understand what kind of data can be convert to `csv` using `ng-csv` directive.
capture

### CODE REVIEW

**Comment by shaohaolin** [comment]
@asafdav I have finished the feature, let me know what you think :)

**Comment by asafdav** [comment]
Hi @shaohaolin sorry it's was rough recently, would you mind squashing your commits ? 
in the meantime I'll start reviewing your pull request, seems awesome

**Comment by shaohaolin** [comment]
@asafdav Thank you for the reply!!! I don't mind to squash the commits. But how can I do that? What' the general steps?

**Comment by karrde00** [comment]
@shaohaolin here is a link explaining how to do it. http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by shaohaolin** [comment]
I am going to squash the commits and make a new one.

**Pull request closed without merging**
