### PR TITLE
Better Safari Support

### PR DESCRIPTION
**Pull request by dvalentiate**
Safari does strange things but with this, it seems more agreeable.

Using a target on the link, Safari now opens a new tab for the download instead of using the same window/tab.

This is beneficial because once in the download state, Safari seemed to forget its cookies and users for our site were forced to log in again. But with the download on the new tab, the user can continue on and it all feels pretty much like it should.

I have been able to test Chrome 40 and Firefox Developer Edition 37 and they continue to work the same as before, offering a download prompt or showing the download immediately, without any new tab showing. Safari 8 shows the new tab with the file content inside of it, "save as" works.

### CODE REVIEW

**Comment by chesleybrown** [comment]
Why not just use `_blank` instead of generating a random frame name to simulate it?

http://www.w3schools.com/tags/att_a_target.asp

**Comment by dvalentiate** [comment]
Because I had completely forgotten about that! Thanks!

**Comment by asafdav** [comment]
@chesleybrown Thank you, @dvalentiate can you please update your pull request accordingly? I'll merge it. Awesome job

**Comment by chesleybrown** [comment]
After some additional testing with this workaround I've discovered it has a caveat. If the user has "Block pop-up windows" enabled in Safari (which I believe is the default) then the directive link silently fails. If I disable "Block pop-up windows" it works as expected.

So if you do add this setting, it might be better to at least make it an optional setting as it seems to completely break downloading in Safari by default.

This is related to how you generate an anchor tag with a target and then click it using JS. I haven't tested it, but a possible workaround would be to not dynamically generate the anchor tag like that and instead apply those `attr` values to the `ng-csv` element itself. Then as long as `ng-csv` is used on an anchor tag this `target=_blank` might work correctly?

**Comment by asafdav** [comment]
I see, interesting idea. I'll have to test it out and see if it works and doesn't break anything. 

I suggest we merge this pull request (after the necessary changes) and open an issue regarding the "block pop-up windows" option in Safari.

**Comment by dvalentiate** [comment]
ok. _blank is implemented. Thanks @chesleybrown.  Interesting point about Safari's block pop-ups behaviour. I like the idea of merging this and opening a new ticket for the pops-up blocking.

**Comment by asafdav** [comment]
@dvalentiate  can you please squash your commits?

**Comment by dvalentiate** [comment]
squashed

**Comment by asafdav** [comment]
Thank you!

**Pull request merged**
