### PR TITLE
Better Excel compability

### PR DESCRIPTION
**Pull request by eugenpodaru**
Hi David,

I am using your library in a project and it's very nice, saved me some work :). However, our users mostly use Excel and there are two problems with Excel:
 - it does not properly open the file unless you explicitly state the separator you are using on the first line with 'sep=SEPARATOR'
- it does not play well with utf-8, so we needed utf-16le. But since we are getting the data from somewhere else, we get it in utf-8, and we needed to re-encode it.

I made some modifications to address these problems:
- I added the possibility to add the separator on the first line with the add-sep attribute (just like add-bom)
- I implemented some encoding methods for utf-8, utf-16, utf-16le and utf-16be so that when these charsets are used, it returns a correctly encoded file.

I need these fixes, so for now I will use my repository, but if you choose to put them in the main repository, it would be great.

Cheers,
Eugen

### CODE REVIEW

**Comment by Phoenix1978** [comment]
hello, 
I have the same problem as you. I tried also with charset="windows-1252" or iso-8859-1 or ANSI or ansi.
I also tried to change the charset directly in the JS code :+1: 
...
          var charset = scope.charset || "windows-1252";
...
everywhere utf-8 was present, but at the end, it seems to not use the given charset, using all the time the UTF-8. Is there something to do previously to specify the charset?

Thanks

**Comment by eugenpodaru** [comment]
@Phoenix1978 

Hi,

You can check my fork https://github.com/eugenpodaru/ng-csv. I have added some code to convert between different charsets. I use \t as field separator, utf-16le as charset, and I also add the BOM, and it works perfectly for me.

Eugen

**Comment by Phoenix1978** [comment]
Thanks a lot, it works well.

**Comment by Phoenix1978** [comment]
Can I ask you another question, I try to load your fork version directly using bower with this address: https://github.com/eugenpodaru/ng-csv.git
But it don't get the version I can download via the relevant button or via the github website directly. 

Do you know which address i had to put to automatically get via bower the last version?

**Comment by eugenpodaru** [comment]
@Phoenix1978 

Hi,

You need to prepend the commit id (hash) https://github.com/eugenpodaru/ng-csv.git#a2aea1f

Regards,
Eugen

**Comment by Phoenix1978** [comment]
Ok I understand better, thanks again

**Comment by eugenpodaru** [comment]
@Phoenix1978 

Hi,

When you put https://github.com/eugenpodaru/ng-csv.git in bower it will take the latest tagged commit. So in order for that to work I should increase the version number and tag the latest commit.

But I want to be in synch with the original repository when it comes to versioning, so that's why I did not do that.

Eugen

**Comment by eirikb** [comment]
@eugenpodaru Did you not go through with this PR? I think this should definitely be added to the library, it is great!  
I've been trying to add a region-independent solution, and as far as [I can see](http://stackoverflow.com/questions/20395699/sep-statement-breaks-utf8-bom-in-csv-file-which-is-generated-by-xsl) the best solution is *UTF16-le* with `\t` as separator.

**Comment by eugenpodaru** [comment]
@eirikb Yes, the solution that worked for me was UTF16-le and \t as separator. My fork has support for encoding to UTF16-le.

As for the PR, I need to rethink how the encoding is integrated with the solution before I make another PR.

**Pull request closed without merging**
